CREATE DATABASE darts;

USE darts;

CREATE TABLE player (
    id INT PRIMARY KEY AUTO_INCREMENT UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL UNIQUE
) Engine = InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE game (
    id INT PRIMARY KEY AUTO_INCREMENT UNIQUE NOT NULL,
    `date` DATETIME NOT NULL
) Engine = InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE played (
    id INT PRIMARY KEY AUTO_INCREMENT UNIQUE NOT NULL,
    game_id INT NOT NULL,
    player_id INT NOT NULL,
    winner BOOLEAN NOT NULL,
    FOREIGN KEY (game_id) REFERENCES game (id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (player_id) REFERENCES player (id)
        ON UPDATE CASCADE ON DELETE CASCADE
) Engine = InnoDB DEFAULT CHARSET=UTF8;
